winget install --id Bitwarden.Bitwarden
winget install --id CPUID.HWMonitor
winget install --id Canonical.Ubuntu
winget install --id Discord.Discord
winget install --id Docker.DockerDesktop
winget install --id Gimp.Gimp
winget install --id Git.Git
winget install --id GitHub.GitLFS
winget install --id Google.Chrome
winget install --id Microsoft.WindowsTerminal
winget install --id Mozilla.Firefox
winget install --id Microsoft.Office
winget install --id Microsoft.PowerToys
winget install --id OBSProject.OBSStudio
winget install --id Valve.Steam
winget install --id SumatraPDF.SumatraPDF
winget install --id Microsoft.Teams
winget install --id Microsoft.VisualStudioCode --override "/silent /mergetasks=""addcontextmenufiles,addcontextmenufolders,addtopath,assiciatewithfiles"""
winget install --id JAMSoftware.TreeSize.Free
winget install --id UnityTechnologies.UnityHub
winget install --id Twilio.Authy
winget install --id SlackTechnologies.Slack
winget install --id WinSCP.WinSCP
winget install --id Keybase.Keybase
winget install --id Google.ChromeRemoteDesktop
winget install --id Microsoft.PowerShell
winget install --id Google.JapaneseIME
winget install --id Microsoft.PowerToys
winget install --id Cloudflare.Warp
winget install --id Nvidia.Broadcast
winget install --id Nvidia.GeForceExperience
winget install --id VideoLAN.VLC
winget install --id OpenVPNTechnologies.OpenVPN
winget install --id Parsec.Parsec
winget install --id Spotify.Spotify
winget install --id 9NVMNJCR03XV # MSI Center
